# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
          npm i
      
    - name: Build
      run: |
        rm -rf docs
        npm run build -o docs
        echo "pycones.pixelmouse.es" > docs/CNAME
      
    - name: Deploy
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f docs
        git commit -m "Deploy CI"
        git push origin main
